export enum HighBeamState {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  DISABLED_LIGHT_DETECTED = 'DISABLED_LIGHT_DETECTED',
  DISABLED_SPEED_LIMIT = 'DISABLED_SPEED_LIMIT',
  FAILURE = 'FAILURE'
}
